[package]
name = "globe"
version = "0.3.0"
authors = ["adamsky <adamsky@enum.space>"]
edition = "2018"
rust-version = "1.70"
repository = "https://github.com/24bit192kHz/globe"
homepage = "https://github.com/24bit192kHz/globe"
documentation = "https://docs.rs/globe"
description = "Customizable ASCII globe generator."
categories = ["graphics", "visualization"]
keywords = ["ascii", "globe", "terminal", "rendering", "planets"]
readme = "README.md"
license = "GPL-3.0"

[lints]
workspace = true
